#指明注册中心的位置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8769/eureka/


#当前项目部署的端口
server:
  port: 8765

#当前项目的名称
spring:
  application:
    name: service-feign

#打开Feign中的断路器
feign:
  hystrix:
    enabled: true
